apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentfrontend-deployment
  labels:
    app: studentfrontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studentfrontend
  template:
    metadata:
      labels:
        app: studentfrontend
    spec:
      containers:
        - name: studentfrontend-container
          image: th1enlm02/student-frontend:latest
          ports:
            - containerPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentbackend-deployment
  labels:
    app: studentbackend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studentbackend
  template:
    metadata:
      labels:
        app: studentbackend
    spec:
      containers:
        - name: studentbackend-container
          image: th1enlm02/student-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: studentdb
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: th1enlm02_root

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: mysql:8.3.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: studentdb
            - name: MYSQL_USER
              value: th1enlm02
            - name: MYSQL_PASSWORD
              value: th1enlm02
            - name: MYSQL_ROOT_PASSWORD
              value: th1enlm02_root
            - name: MYSQL_HOST
              value: mysql-container
              
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin-container
          image: phpmyadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: PMA_HOST
              value: mysql
            - name: MYSQL_ROOT_PASSWORD
              value: th1enlm02_root